version: '2.4'

services:
  async-rest-server:
    image: 'vertx-async-rest'
    container_name: async-rest-server
    ports:
      - "8123:8123"
    environment:
      - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+UnlockDiagnosticVMOptions -XX:NativeMemoryTracking=summary -XX:+PrintNMTStatistics
      - CONFIG_LOCATION=/opt/async-rest-server/docker-app-config.json
      - requests.file.path=requests
      - responses.file.path=responses
    restart: on-failure
    network_mode: "bridge"
    mem_limit: 512M
    cpu_percent: 30
    volumes:
      - "./docker-app-config.json:/opt/async-rest-server/docker-app-config.json"
